### ISSUE TITLE
Have no notification appear in UI

### ISSUE THREAD

**Issue by MadEddieFFS** [NePheus/capacitor-fullscreen-notification#1]
Excellent plugin - perfect for my needs - I just wondered.

Is it possible for this plugin to NOT display any kind of UI when it receives the data only push message? I was hoping to use my own UI to display an "Incoming Call" screen instead. The plugin is perfect for all scenarios except if the phone screen is off, as an incoming call requires a little more than a simple notification - any input would be appeciated.

Also - is there anymore information on the usage of "fullScreenId" , "ChannelId" and "channelName" parts of the notification? It almost suggests your plugin could find an inbuild Android activity based on this fullscreenId ?

**Comment by NePheus** [comment]
I dont know if I understand your question correctly.

Some information that may help you:
- Any data push notification will be processed, that contains the field 'fullScreenId'
- A local notification in fullscreen mode (that means, that the main activity will be launched) will be triggered by the plugin and its not possible to change this behavior because its handled by Android
- If your phone is unlocked and not in standby, Android will show a heads up notification (the default bar that drops from the top) instead of launching the app. It will only launch the app when you click on it.
- If your phone is locked, the app will be launched instantly and you could show an own UI for your phone call.
- The property 'fullScreenId' is an identifier, so you can do anything inside your listener. I.e. if you want to trigger a door bell event and a ring event, you should set different fullScreenIds, because the same listener will be triggered in typescript and you can distinguish them.
- Set android:turnScreenOn="true" in your AndroidManifest.xml to let the notification turn your screen on when you are in standby.
- Set android:showWhenLocked="true" in your AndroidManifest.xml to let the notification showed over (like z-index) the lock screen, otherwise it will be hidden and you will only see it after unlocking.

Regarding the channel properties: https://developer.android.com/develop/ui/views/notifications/channels

**Comment by MadEddieFFS** [comment]
Thanks for the quick and detailed response. I think I am asking for something outside of what this plugin is intended for.

I wondered if it is possible for this plugin to skip the local notification and just callback to the application (making it full screen if required)? Is that possible within Android ?

**Comment by NePheus** [comment]
To be honest I dont know, because im no Android expert on a deep level. Whats exactly the issue in your case? Do you want to launch the app when your phone is unlocked instead of showing the heads up notification that has been triggered by the local notification? I just saw at another phone app, that also uses the heads up notification and just show 2 buttons for direct actions - accept, abort (or launching the app by clicking on the notification). You could also define buttons for the heads up with this plugin.

**Comment by MadEddieFFS** [comment]
I suppose my aim is - when a push notification is received the application should be launched and show in full screen. I am basically trying to mimic the existing "Incoming Call" process of Android. If you plugin didn't show a local notification and just re-launched the application (as if the Accept button had been pressed on the notification) then I'm 99% there. The problem is when the phone is locked - a single notification "ping" won't quite grab the users attention for an incoming call.

**Comment by NePheus** [comment]
When the phone is locked, the heads up notification will not be shown, as I described. Then the app will launch. The heads up will just show when the user has the phone in the hand and its unlocked. In my case I use this for the door bell and I also pass a vibrationPattern (see readme). My phone always vibrates in both cases, when the app is launched and also when the heads up is displayed, because its binded to the localnotification itself. There were not just one notification that did not grab my attention :)

My use case: On door bell my phone starts the app/heads up and will auto close it after 10 seconds (see property "timeout"). In this time it vibrates by the set pattern. When the app was launchend and I click anywhere on the screen, I use the method "cancelNotification" and the vibrations stop afterwards.

**Comment by MadEddieFFS** [comment]
When debugging my app on a physical device over adb there is no alert at all when the mobile is not in hand and the screen is off. I am sure the FCM data message is being received because when I wake up the device it loads the app instantly. Do you know why no alert/notification occurs ? Also - Do you know how to change the local notification to make a "ringing" sound ? My attempt (below) didn't make a difference: 

NotificationCompat.Builder notification = new NotificationCompat.Builder(getApplicationContext(), channel.getId())
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                    .setCategory(NotificationCompat.CATEGORY_CALL)
                    .setSmallIcon(getResources().getIdentifier("ic_launcher", "mipmap", getPackageName()))
                    .setContentTitle(title)
                    .setContentText(text)
                    .setAutoCancel(true)
                    .setOngoing(true)
                    .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE))
                    .setFullScreenIntent(createPendingIntent(this, PENDING_INTENT_REQUEST_CODE, notificationIntentData), true);

**Comment by NePheus** [comment]
> I am sure the FCM data message is being received

This sounds like the missing attributes in the AndroidManifest.xml. Are you sure you added the `android:turnScreenOn="true"` and `android:showWhenLocked="true"` to your activity?
```
<manifest ...>
    <application ...>
        <activity
            ...
            android:showWhenLocked="true"
            android:turnScreenOn="true">
        </activity>
    </application>
</manifest>

```

> Do you know how to change the local notification to make a "ringing" sound?

Well, thats a good question. I only use vibration on my device, so I never tested it. If its really missing, it could be added as a new feature request ticket.
The vibration feature is added to the android channel itself:
https://github.com/NePheus/capacitor-fullscreen-notification/blob/master/android/src/main/java/nepheus/capacitor/fullscreennotification/MessagingService.java#L133
There is also a setSound method, maybe its working on the channel:
https://developer.android.com/reference/android/app/NotificationChannel#setSound(android.net.Uri,%20android.media.AudioAttributes)

But you could also try to go to the system settings, open the app, then notifications and then click on your new channel that was added by this plugin. There are also some settings like sound. Maybe its also possible to setup there something.

**Comment by MadEddieFFS** [comment]
That fixed it - I had put those settings within the application XML node not the activity. The phone now instantly displays the application when a notification is received. Thanks for your help.

I'm still trying with the sound issue. Whilst I am able to add the same line of code (setSound(....) ) to the channel the code does not compile...I will continue looking

![image](https://user-images.githubusercontent.com/4107761/206129263-7f0c5ed9-2c3a-4da3-a212-e7c1372897bf.png)

**Comment by NePheus** [comment]
Maybe this works:
`channel.setSound(PreferencesManager.getNotificationRingTone(context), null);`

**Comment by MadEddieFFS** [comment]
Thanks for the help though this one didn't work :( This is a great plugin and I really appreciate the help
